title: github page practice
author: 김동건
subtitle: 202011397_김동건 github page practice

url: "https://thisistaewon.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://rahulbothra.com/cv.pdf"
